'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import store  from "./components/redux/store";
import { Provider } from "react-redux";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Walters Portfolio",
  description: "Generated by the powerful framework of NEXtjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head> */}
        {/* <title> {metadata.title} </title>  */}
        {/* <meta name = "description" content={metadata.description} /> */}
      {/* </Head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      <Provider store={store}>
        {children}
        </Provider>
      </body>
    </html>
  );
}
